@Identity.API_HostAddress = https://localhost:7027


POST {{Identity.API_HostAddress}}/api/identities/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin123!@#",
  "rememberMe": true
}

###
